export * from './books/books.component';
export * from './header/header.component';
export * from './search-component/search-component.component';
export * from './dashboard/dashboard.component';
export * from './book-detail/book-detail.component';
export * from '../modules/AuthModule/components/login/login.component';
export * from './bookstore/bookstore.component';
export * from './laptopstore/laptopstore.component';
export * from './laptop/laptop.component';
